### ISSUE TITLE
Refactor / cleanup code

### ISSUE THREAD

**Issue by aewens** [aewens/tunnel.js#1]
This was a fun utility a made a few months ago. It's essentially an abstraction layer on top of postMessage to allow for bi-directional communication between websites on the client-side. In this project **a** (alpha) represents a third-party talking to **b** (beta) a service with tunnel.js setup with commands its willing to perform. 

What this issue is for is mainly the code in app.js on alpha and beta, refactoring the **listener** function that holds the commands/callbacks used for communication. However, any improvements that makes the code more readable / useful in the context of this project will be applicable here.

This issue was opened in the spirit of Hacktoberfest, so I'll keep this issue open so anyone who wants to contribute can give it a shot (and feel free to ask questions as well!)

**Comment by kritisingh1** [comment]
Can I take this up ?

**Comment by aewens** [comment]
@kritisingh1 Definitely!

**Comment by braxtonchristensen** [comment]
Are you trying to stay away from ES6?

**Comment by aewens** [comment]
@braxtonchristensen At the time I just wanted something simple since this is client-side only and I wanted it to "Just Work" on most browsers. If you want to add ES6, just add in something in package.json that will transpile it into ES5.
